/** Re-exports the shared SDK layer's public types, so this package's public API stays put. */
export {
  APPDUCT_DEFAULT_TOOL_TIMEOUT_MS,
  jsonSchema,
  AppductBootstrapParseError,
  AppductDisabledError,
} from "@appduct/shared/sdk";
export type {
  AppductClientState,
  AppductConnectOptions,
  AppductBuildConfig,
  AppductBootstrapConnectInput,
  AppductConnectInput,
  AppductConnectCallOptions,
  AppductBootstrapParseErrorCode,
  AppductListenerKind,
  AppductUnifiedStateChangeEvent,
  AppductSessionChangeEvent,
  AppductUnifiedErrorEvent,
  AppductUnifiedListenerMap,
  AppductReportProgress,
  AppductToolExecutionContext,
  AppductToolHandler,
  AppductJsonSchemaObject,
  AppductJsonSchemaConverter,
  AppductPairedSchema,
  AppductRuntimeSchema,
  AppductNormalizedToolSchema,
  InferToolArgs,
  InferToolResult,
  AppductToolDefinition,
  AppductToolRegistration,
  AppductEventDefinition,
  AppductRegisteredEvent,
  AppductRegisteredTool,
} from "@appduct/shared/sdk";
