#import <CordieriteSpec/CordieriteSpec.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTInvalidating.h>

#if __has_include("Cordierite-Swift.h")
#import "Cordierite-Swift.h"
#elif __has_include(<Cordierite/Cordierite-Swift.h>)
#import <Cordierite/Cordierite-Swift.h>
#else
#error Cordierite's autogenerated Swift header cannot be found. Try rebuilding Pods and verify the pod module name is Cordierite.
#endif

using namespace facebook::react;

@interface RCTNativeCordierite : NativeCordieriteSpecBase <NativeCordieriteSpec, RCTInvalidating> {
  CordieriteTurboBridge *_swift;
}
@end

@implementation RCTNativeCordierite

RCT_EXPORT_MODULE(Cordierite)

- (instancetype)init
{
  if (self = [super init]) {
    _swift = [[CordieriteTurboBridge alloc] init];
    __weak __typeof__(self) weakSelf = self;
    [_swift
        wireEventHandlersWithToolCall:^(NSString *callId, NSString *name, NSString *argsJson) {
          [weakSelf emitOnToolCall:@{@"id" : callId, @"name" : name, @"argsJson" : argsJson}];
        }
        toolCancel:^(NSString *callId, NSString *reason) {
          [weakSelf emitOnToolCancel:@{@"id" : callId, @"reason" : reason}];
        }
        stateChange:^(NSString *state, NSString *reason) {
          NSMutableDictionary *payload = [NSMutableDictionary dictionaryWithObject:state forKey:@"state"];
          if (reason != nil) {
            payload[@"reason"] = reason;
          }
          [weakSelf emitOnStateChange:payload];
        }
        sessionChange:^(NSString *type, NSString *sessionId, NSString *alias, NSString *reason) {
          NSMutableDictionary *payload = [NSMutableDictionary dictionaryWithDictionary:@{
            @"type" : type,
            @"sessionId" : sessionId != nil ? sessionId : [NSNull null],
            @"alias" : alias != nil ? alias : [NSNull null],
          }];
          if (reason != nil) {
            payload[@"reason"] = reason;
          }
          [weakSelf emitOnSessionChange:payload];
        }
        error:^(NSDictionary *payload) {
          [weakSelf emitOnError:payload];
        }];
  }
  return self;
}

- (std::shared_ptr<TurboModule>)getTurboModule:(const ObjCTurboModule::InitParams &)params
{
  return std::make_shared<NativeCordieriteSpecJSI>(params);
}

#pragma mark - NativeCordieriteSpec

- (void)registerTool:(NSString *)descriptorJson
{
  NSError *error = nil;
  [_swift registerToolWithDescriptorJson:descriptorJson error:&error];
  if (error != nil) {
    @throw [NSException exceptionWithName:@"CordieriteError" reason:error.localizedDescription userInfo:nil];
  }
}

- (void)unregisterTool:(NSString *)name
{
  [_swift unregisterToolWithName:name];
}

- (NSNumber *)handleUrl:(NSString *)url
{
  return @([_swift handleUrl:url]);
}

- (void)connect:(NSString *)inputJson
      supersede:(BOOL)supersede
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject
{
  [_swift connectWithInputJson:inputJson supersede:supersede resolve:resolve reject:reject];
}

- (void)restoreSession:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [_swift restoreSessionWithResolve:resolve reject:reject];
}

- (void)disconnect:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [_swift disconnectWithResolve:resolve reject:reject];
}

- (void)postEvent:(NSString *)name
      payloadJson:(NSString *)payloadJson
          resolve:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject
{
  [_swift postEventWithName:name payloadJson:payloadJson resolve:resolve reject:reject];
}

- (void)respondToToolCall:(NSString *)callId resultJson:(NSString *)resultJson errorJson:(NSString *)errorJson
{
  [_swift respondToToolCallWithId:callId resultJson:resultJson errorJson:errorJson];
}

- (void)reportToolProgress:(NSString *)callId progress:(NSNumber *)progress message:(NSString *)message
{
  [_swift reportToolProgressWithId:callId progress:progress message:message];
}

- (NSString *)getState
{
  return (NSString *)[_swift getState];
}

- (NSString *)getSessionId
{
  return [_swift getSessionId];
}

- (NSString *)getRegisteredToolsJson
{
  return (NSString *)[_swift getRegisteredToolsJson];
}

#pragma mark - Constants

// Codegen special-cases `getConstants()` (legacy bridge constants export): the generated
// `NativeCordieriteSpec` protocol requires both `constantsToExport` and `getConstants`, mirroring
// e.g. RN core's `RCTAppState`. `[self getConstants]` reads the Swift/Bundle-backed build config
// each call rather than caching it, matching `getState`/`getSessionId` above.
- (facebook::react::ModuleConstants<JS::NativeCordierite::Constants::Builder>)constantsToExport
{
  return (facebook::react::ModuleConstants<JS::NativeCordierite::Constants::Builder>)[self getConstants];
}

- (facebook::react::ModuleConstants<JS::NativeCordierite::Constants::Builder>)getConstants
{
  NSDictionary *config = [_swift getConstants];
  return (facebook::react::ModuleConstants<JS::NativeCordierite::Constants::Builder>)facebook::react::typedConstants<JS::NativeCordierite::Constants>({
      .trust = (NSString *)config[@"trust"],
      .hasEmbeddedPins = [config[@"hasEmbeddedPins"] boolValue],
      .allowPrivateLanOnly = [config[@"allowPrivateLanOnly"] boolValue],
  });
}

#pragma mark - RCTInvalidating

- (void)invalidate
{
  [_swift invalidate];
}

@end
